cloud storage導入

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -5,7 +5,7 @@ on:
     tags:
       - 'v*.*.*'
   workflow_run:
-    workflows: ["Increment Version"]
+    workflows: ['Increment Version']
     types:
       - completed
 
@@ -16,57 +16,57 @@ jobs:
       name: production
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: '20'  # @types/nodeのバージョンに合わせて更新
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '20' # @types/nodeのバージョンに合わせて更新
 
-    - name: Install pnpm
-      run: npm install -g pnpm
+      - name: Install pnpm
+        run: npm install -g pnpm
 
-    - name: Install dependencies
-      run: |
-        cd ./mahjong-hono  # 必要に応じてディレクトリを変更
-        pnpm install
+      - name: Install dependencies
+        run: |
+          cd ./mahjong-hono  # 必要に応じてディレクトリを変更
+          pnpm install
 
-    - name: Run ESLint
-      run: |
-        cd ./mahjong-hono  # 必要に応じてディレクトリを変更
-        pnpm run lint
-      continue-on-error: false  # エラーがあれば処理を中断
+      - name: Run ESLint
+        run: |
+          cd ./mahjong-hono  # 必要に応じてディレクトリを変更
+          pnpm run lint
+        continue-on-error: false # エラーがあれば処理を中断
 
-    - name: Set up Cloud SDK
-      uses: google-github-actions/setup-gcloud@v0.2.0
-      with:
-        project_id: ${{ secrets.GCP_PROJECT_ID }}
-        service_account_key: ${{ secrets.GCP_SA_KEY }}
-        export_default_credentials: true
+      - name: Set up Cloud SDK
+        uses: google-github-actions/setup-gcloud@v0.2.0
+        with:
+          project_id: ${{ secrets.GCP_PROJECT_ID }}
+          service_account_key: ${{ secrets.GCP_SA_KEY }}
+          export_default_credentials: true
 
-    - name: Extract tag version
-      id: extract_tag
-      run: |
-        TAG_VERSION=${GITHUB_REF#refs/tags/}
-        latest_tag=$(git tag -l --sort -refname --sort -authordate | head -1)
+      - name: Extract tag version
+        id: extract_tag
+        run: |
+          TAG_VERSION=${GITHUB_REF#refs/tags/}
+          latest_tag=$(git tag -l --sort -refname --sort -authordate | head -1)
 
-        if [[ ! "$TAG_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          TAG_VERSION=${latest_tag}
-        fi
+          if [[ ! "$TAG_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            TAG_VERSION=${latest_tag}
+          fi
 
-        if [[ ! "$TAG_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Invalid tag format. Must be v{major}.{minor}.{patch} with numeric values."
-          exit 1
-        fi
-        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
+          if [[ ! "$TAG_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid tag format. Must be v{major}.{minor}.{patch} with numeric values."
+            exit 1
+          fi
+          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
 
-    - name: Submit Cloud Build
-      working-directory: ./mahjong-hono
-      run: |
-        gcloud builds submit \
-          --region asia-east1 \
-          --config cloudbuild.yaml \
-          --substitutions=_TAG_VERSION=${{ env.TAG_VERSION }},_DATABASE_URL=${{ secrets.DATABASE_URL }}
+      - name: Submit Cloud Build
+        working-directory: ./mahjong-hono
+        run: |
+          gcloud builds submit \
+            --region asia-east1 \
+            --config cloudbuild.yaml \
+            --substitutions=_TAG_VERSION=${{ env.TAG_VERSION }},_DATABASE_URL=${{ secrets.DATABASE_URL }},_GCS_SA_KEY_PATH=${{ secrets.GCS_SA_KEY_PATH }},_GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }},_GCS_SA_KEY_OBJECT=${{ secrets.GCS_SA_KEY_OBJECT }}
